name: Ensure Site Builds Cleanly
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install GraphicsMagick
        run: sudo apt install graphicsmagick
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Restore Asset Caches
        uses: actions/cache@v2
        with:
          key: if-cache
          path: |
            ./if-cache
            ./twitter-cache.json
      - run: npm ci
      - run: npm test
      - run: npm run build
